version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: just_nil_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: just_nil
      POSTGRES_USER: just_nil
      POSTGRES_PASSWORD: just_nil
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
